research_company_task:
  description: >
    Use a searh tool to look up this company's stock information: {company_name}.
    The goal is to prepare enough information to make an informed analysis of the company's stock performance.
  expected_output: >
    All of the relevant financial information about the company's stock performance.

analyse_company_task:
  description: >
    Take {company_name}'s financial information, analyse it, and provide a financial analysis, including: Profitability ratio,
    Liquidity ratios, Solvency ratios, Efficiency ratios, Growth metrics, Valuation metrics, and  Cash
  expected_output: >
    A nicely formatted analysis including all of the financial metrics necessary for a thorough financial analysis available.
